repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.9
        args: [--line-length=88]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black, --filter-files]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10]
        args: [--max-line-length=88, --ignore=E203, --max-complexity=18]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--ignore-missing-imports, --disallow-untyped-defs]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
    -   id: prettier
        types_or: [javascript, css, scss, html, json, yaml, markdown, mdx]
        args: [--write, --no-semi, --single-quote, --print-width=100]

-   repo: local
    hooks:
    -   id: pytest-check
        name: Run tests
        entry: pytest -xvs --tb=native --cov=app --no-cov-on-fail --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
