version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    command: flask run --host=0.0.0.0 --port=5000 --debugger --reload
    volumes:
      - .:/app
      - /app/instance
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=punk_eco_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d punk_eco_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data_dev:/data

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data_dev:
  redis_data_dev:
